kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: outlooktoslack-pv-claim
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi